services:
  - type: web
    name: django_project
    env: docker
    dockerImage: gurbanoglu/django_project:latest
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.django_project.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false