# Generated by Django 4.1 on 2025-04-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_text', models.CharField(max_length=220, verbose_name='Question')),
                ('m_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('m_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.exam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_text', models.CharField(max_length=220, verbose_name='Answer')),
                ('m_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('m_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('m_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamQuestions.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Exam Answer',
                'verbose_name_plural': 'Exam Answers',
            },
        ),
    ]
