# Generated by Django 4.0.5 on 2022-07-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examanswer',
            options={'verbose_name_plural': 'Exam Answers'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'verbose_name_plural': 'Exam Questions'},
        ),
    ]
