# Generated by Django 4.0.5 on 2022-07-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0002_alter_examanswer_options_alter_examquestion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='exam_text',
            new_name='Exam_Question',
        ),
    ]
