# Generated by Django 4.0.5 on 2022-07-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0003_rename_exam_text_examquestion_exam_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='Exam_Question',
            new_name='exam_text',
        ),
    ]
