# Generated by Django 4.0.5 on 2022-07-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0004_rename_exam_question_examquestion_exam_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='exam_text',
            new_name='Exam_Answer',
        ),
        migrations.RenameField(
            model_name='examquestion',
            old_name='exam_text',
            new_name='Exam_Question',
        ),
    ]
