# Generated by Django 4.0.5 on 2022-07-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0005_rename_exam_text_examanswer_exam_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='question',
            new_name='Question',
        ),
    ]
