# Generated by Django 4.0.5 on 2022-07-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0006_rename_question_examanswer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='Question',
            new_name='question',
        ),
    ]
