# Generated by Django 4.0.5 on 2022-07-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0007_rename_question_examanswer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='Exam_Answer',
            new_name='exam_text',
        ),
        migrations.RenameField(
            model_name='examquestion',
            old_name='Exam_Question',
            new_name='exam_text',
        ),
    ]
