# Generated by Django 4.0.5 on 2022-07-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_alter_exam_time_limit'),
        ('ExamQuestions', '0008_rename_exam_answer_examanswer_exam_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Exam Answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=220)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.exam')),
            ],
            options={
                'verbose_name_plural': 'Exam Questions',
            },
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='exam',
        ),
        migrations.DeleteModel(
            name='ExamAnswer',
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamQuestions.question'),
        ),
    ]
