# Generated by Django 4.0.5 on 2022-07-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0010_alter_answer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Exam Answer', 'verbose_name_plural': 'Exam Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Exam Question', 'verbose_name_plural': 'Exam Questions'},
        ),
    ]
