# Generated by Django 4.0.5 on 2022-08-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0011_alter_answer_options_alter_question_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='m_correct',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='created',
            new_name='m_created',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='m_question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='m_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created',
            new_name='m_created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='exam',
            new_name='m_exam',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='m_text',
        ),
    ]
