# Generated by Django 4.0.5 on 2022-08-31 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0011_alter_exam_m_difficulty_alter_exam_m_examname_and_more'),
        ('ExamQuestions', '0012_rename_correct_answer_m_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='m_correct',
            field=models.BooleanField(default=False, verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='m_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='m_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamQuestions.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='m_text',
            field=models.CharField(max_length=220, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='m_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='m_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='m_text',
            field=models.CharField(max_length=220, verbose_name='Text'),
        ),
    ]
