# Generated by Django 4.0.5 on 2022-09-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0013_alter_answer_m_correct_alter_answer_m_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='m_text',
            field=models.CharField(max_length=220, verbose_name='Question'),
        ),
    ]
