# Generated by Django 4.0.5 on 2022-09-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamQuestions', '0014_alter_question_m_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='m_text',
            field=models.CharField(max_length=220, verbose_name='Answer'),
        ),
    ]
