# Generated by Django 4.1 on 2025-04-09 13:40

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('m_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Map Database',
                'verbose_name_plural': 'Map Databases',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.CharField(max_length=100, verbose_name='Title')),
                ('m_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('m_url', embed_video.fields.EmbedVideoField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-m_added'],
            },
        ),
    ]
