# Generated by Django 4.0.5 on 2022-07-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdatabase',
            options={'verbose_name': 'Map Database', 'verbose_name_plural': 'Map Databases'},
        ),
    ]
