# Generated by Django 4.0.5 on 2022-08-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-added']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='m_added',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='m_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='m_url',
            new_name='url',
        ),
    ]
