# Generated by Django 4.0.5 on 2022-08-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0006_alter_video_options_rename_m_added_video_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='m_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='m_date',
            new_name='date',
        ),
    ]
