# Generated by Django 4.0.5 on 2022-08-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_rename_m_address_mapdatabase_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-m_added']},
        ),
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='address',
            new_name='m_address',
        ),
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='date',
            new_name='m_date',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='added',
            new_name='m_added',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='m_title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='m_url',
        ),
    ]
