# Generated by Django 4.0.5 on 2022-08-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0008_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='m_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='m_date',
            new_name='date',
        ),
    ]
