# Generated by Django 4.0.5 on 2022-08-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0009_rename_m_address_mapdatabase_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='address',
            new_name='m_address',
        ),
        migrations.RenameField(
            model_name='mapdatabase',
            old_name='date',
            new_name='m_date',
        ),
    ]
