# Generated by Django 4.0.5 on 2022-08-31 04:02

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0010_rename_address_mapdatabase_m_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdatabase',
            name='m_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='mapdatabase',
            name='m_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='m_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='video',
            name='m_title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='m_url',
            field=embed_video.fields.EmbedVideoField(verbose_name='URL'),
        ),
    ]
