# Generated by Django 4.1 on 2025-04-09 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_Profile_Image', models.ImageField(default='DefaultProfileImage.jpg', upload_to='profile_pics', verbose_name='Profile Image')),
                ('m_Facial_Image', models.ImageField(default='DefaultFacialImage.jpg', upload_to='facial_images', verbose_name='Facial Image')),
                ('m_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
