# Generated by Django 4.1 on 2025-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image',
            field=models.ImageField(default='facial_images/default_facial_image.jpg', upload_to='facial_images/', verbose_name='Facial Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.ImageField(default='profile_images/default_profile_image.jpg', upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
