# Generated by Django 4.1 on 2025-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_m_facial_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.CharField(max_length=500, verbose_name='https://res.cloudinary.com/dybmcxawv/image/upload/v1747033011/profile_images/default_profile_image.png'),
        ),
    ]
