# Generated by Django 4.1 on 2025-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_m_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='m_Facial_Image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='m_Profile_Image',
        ),
        migrations.AddField(
            model_name='profile',
            name='m_Facial_Image_URL',
            field=models.URLField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747033011/profile_images/default_profile_image.png', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='m_Profile_Image_URL',
            field=models.URLField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747033011/profile_images/default_profile_image.png', max_length=500),
        ),
    ]
