# Generated by Django 4.0.5 on 2022-07-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_facial_image_profile_facial_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facial_image',
            new_name='Facial_Image',
        ),
    ]
