# Generated by Django 4.1 on 2025-05-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_m_facial_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image_URL',
            field=models.URLField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747032528/facial_images/default_facial_image.jpg', max_length=500, verbose_name='Facial Image URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image_URL',
            field=models.URLField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747033011/profile_images/default_profile_image.png', max_length=500, verbose_name='Profile Image URL'),
        ),
    ]
