# Generated by Django 4.0.5 on 2022-08-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_facial_image_profile_facial_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='m_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='m_user',
        ),
    ]
