# Generated by Django 4.0.5 on 2022-08-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_image_profile_m_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='m_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='m_user',
            new_name='user',
        ),
    ]
