# Generated by Django 4.1 on 2025-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_m_facial_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image_URL',
            field=models.URLField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747060044/facial_images/default_facial_image.webp', max_length=500, verbose_name='Facial Image URL'),
        ),
    ]
