# Generated by Django 4.0.5 on 2022-08-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_m_image_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Facial_Image',
            new_name='m_Facial_Image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='m_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='m_user',
        ),
    ]
