# Generated by Django 4.1 on 2025-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_m_facial_image_profile_m_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='m_Facial_Image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='m_Profile_Image',
        ),
    ]
