# Generated by Django 4.0.5 on 2022-09-01 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Facial_Image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Profile_Image',
        ),
        migrations.AddField(
            model_name='profile',
            name='m_Facial_Image',
            field=models.ImageField(default='defaultFace.jpg', upload_to='facial_images', verbose_name='Facial Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
