# Generated by Django 4.0.5 on 2022-09-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_facial_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='m_user',
        ),
    ]
