# Generated by Django 4.0.5 on 2022-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_user_profile_m_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image',
            field=models.ImageField(default='DefaultFacialImage.jpg', upload_to='facial_images', verbose_name='Facial Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.ImageField(default='DefaultProfileImage.jpg', upload_to='profile_pics', verbose_name='Profile Image'),
        ),
    ]
