# Generated by Django 4.1 on 2025-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_m_facial_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image',
            field=models.ImageField(default='default_facial_image.jpg', upload_to='facial_images/', verbose_name='Facial Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.ImageField(default='default_profile_image.png', upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
