# Generated by Django 4.0.5 on 2022-09-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
