# Generated by Django 4.1 on 2025-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_m_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.ImageField(null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
