# Generated by Django 4.1 on 2025-05-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_m_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image',
            field=models.ImageField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747068277/facial_images/default_facial_image.jpg', upload_to='facial_images/', verbose_name='Facial Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.ImageField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747033011/profile_images/default_profile_image.png', upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
