# Generated by Django 4.0.5 on 2022-09-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
