# Generated by Django 4.1 on 2025-05-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_profile_m_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='m_Profile_Image_URL',
            field=models.URLField(default='https://res.cloudinary.com/dybmcxawv/image/upload/v1747033011/profile_images/default_profile_image.png', max_length=500, verbose_name='Profile Image URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_Profile_Image',
            field=models.ImageField(upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
