# Generated by Django 4.1 on 2025-05-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_m_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image',
            field=models.ImageField(null=True, upload_to='facial_images/', verbose_name='Facial Image'),
        ),
    ]
