# Generated by Django 4.1 on 2025-05-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_m_facial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_Facial_Image',
            field=models.ImageField(upload_to='facial_images/', verbose_name='Facial Image'),
        ),
    ]
