# Generated by Django 4.1 on 2025-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_examName', models.CharField(max_length=120, verbose_name='Exam Name')),
                ('m_material', models.CharField(max_length=120, verbose_name='Material')),
                ('m_questionCount', models.IntegerField(verbose_name='Question Count')),
                ('m_timeLimit', models.IntegerField(help_text='duration of the exam in minutes', verbose_name='Time Limit')),
                ('m_scoreRequiredToPass', models.IntegerField(help_text='required score in %', verbose_name='Score Required To Pass')),
                ('m_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Challenging', 'Challenging')], max_length=11, verbose_name='Difficulty')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
