# Generated by Django 4.0.5 on 2022-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('question_count', models.IntegerField()),
                ('time_limit', models.IntegerField(help_text='duration of the quiz in minutes')),
                ('score_required_to_pass', models.IntegerField(help_text='required score in %')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('challenging', 'challenging')], max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
