# Generated by Django 4.0.5 on 2022-06-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0002_alter_exam_exam_name_alter_exam_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(help_text='duration of the exam in minutes'),
        ),
    ]
