# Generated by Django 4.0.5 on 2022-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_alter_exam_time_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_name',
            new_name='exam_Name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='question_count',
            new_name='question_Count',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='score_required_to_pass',
            new_name='score_Required_To_Pass',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='time_limit',
            new_name='time_Limit',
        ),
        migrations.AlterField(
            model_name='exam',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Challenging', 'Challenging')], max_length=11),
        ),
    ]
