# Generated by Django 4.0.5 on 2022-07-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0004_rename_exam_name_exam_exam_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
    ]
