# Generated by Django 4.0.5 on 2022-08-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0006_rename_difficulty_exam_m_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='m_exam_Name',
            new_name='m_examName',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='m_question_Count',
            new_name='m_questionCount',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='m_score_Required_To_Pass',
            new_name='m_scoreRequiredToPass',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='m_time_Limit',
            new_name='m_timeLimit',
        ),
    ]
