# Generated by Django 4.0.5 on 2022-08-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0009_alter_exam_m_examname_alter_exam_m_timelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='m_examName',
            field=models.CharField(max_length=120, verbose_name='Exam_Name'),
        ),
    ]
