# Generated by Django 4.0.5 on 2022-08-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0010_alter_exam_m_examname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='m_difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Challenging', 'Challenging')], max_length=11, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='m_examName',
            field=models.CharField(max_length=120, verbose_name='Exam Name'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='m_material',
            field=models.CharField(max_length=120, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='m_questionCount',
            field=models.IntegerField(verbose_name='Question Count'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='m_scoreRequiredToPass',
            field=models.IntegerField(help_text='required score in %', verbose_name='Score Required To Pass'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='m_timeLimit',
            field=models.IntegerField(help_text='duration of the exam in minutes', verbose_name='Time Limit'),
        ),
    ]
