# Generated by Django 4.1 on 2025-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=200, verbose_name='Name')),
                ('m_userID', models.CharField(max_length=1000, verbose_name='User ID')),
                ('m_roomName', models.CharField(max_length=200, verbose_name='Room Name')),
                ('m_insession', models.BooleanField(default=True, verbose_name='In Session')),
            ],
            options={
                'verbose_name': 'Room Member',
                'verbose_name_plural': 'Room Members',
            },
        ),
    ]
