# Generated by Django 4.0.5 on 2022-08-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_roommember_m_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='insession',
            new_name='m_insession',
        ),
    ]
