# Generated by Django 4.0.5 on 2022-08-31 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_roommember_m_insession_alter_roommember_m_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommember',
            options={'verbose_name': 'Room Member', 'verbose_name_plural': 'Room Members'},
        ),
    ]
