# Generated by Django 4.0.5 on 2022-07-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResults', '0004_rename_exam_score_examresult_exam_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='exam_score',
            new_name='exam_Score',
        ),
    ]
