# Generated by Django 4.0.5 on 2022-07-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResults', '0005_rename_exam_score_examresult_exam_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Exam Result', 'verbose_name_plural': 'Exam Results'},
        ),
    ]
