# Generated by Django 4.0.5 on 2022-08-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_post_m_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='m_date_posted',
            new_name='m_datePosted',
        ),
    ]
