# Generated by Django 4.0.5 on 2022-08-31 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_rename_m_date_posted_post_m_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='m_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
